//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        public Dish()
        {
            this.DishIngredients = new HashSet<DishIngredient>();
            this.OrderDishes = new HashSet<OrderDish>();
        }
    
        public int ID_Dish { get; set; }
        public int ID_TypeDish { get; set; }
        public string DishName { get; set; }
        public decimal Price { get; set; }
        public byte[] Photo { get; set; }
        public string Detail { get; set; }
    
        public virtual TypeDish TypeDish { get; set; }
        public virtual ICollection<DishIngredient> DishIngredients { get; set; }
        public virtual ICollection<OrderDish> OrderDishes { get; set; }
    }
}
