//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int ID_Employee { get; set; }
        public int ID_post { get; set; }
        public string FName { get; set; }
        public string EmpName { get; set; }
        public string LName { get; set; }
        public string Phone { get; set; }
        public System.DateTime Birthdate { get; set; }
        public byte[] Photo { get; set; }
        public System.DateTime DateEmployment { get; set; }
        public string Address { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
