//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public Ingredient()
        {
            this.DishIngredients = new HashSet<DishIngredient>();
        }
    
        public int ID_Ingredient { get; set; }
        public string IngridientName { get; set; }
    
        public virtual ICollection<DishIngredient> DishIngredients { get; set; }
    }
}
