//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDishes = new HashSet<OrderDish>();
        }
    
        public int ID_Order { get; set; }
        public int ID_Employee { get; set; }
        public System.DateTime Date { get; set; }
        public string Remarks { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<OrderDish> OrderDishes { get; set; }
    }
}
