//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDish
    {
        public int ID_OrderDish { get; set; }
        public int Dish_ID { get; set; }
        public int ID_Order { get; set; }
        public int Quantity { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Order Order { get; set; }
    }
}
