//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeDish
    {
        public TypeDish()
        {
            this.Dishes = new HashSet<Dish>();
        }
    
        public int ID_TypeDish { get; set; }
        public string TypeDishName { get; set; }
        public string Detailed { get; set; }
    
        public virtual ICollection<Dish> Dishes { get; set; }
    }
}
